module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-unstable
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ! 'Hackage: primes 0.2.1.0'
ghc-args: []
excluded-modules: []
